@jwt_admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyMTExNTJ9.cdtT6WuNP9YUD7eZeJhEfx0BZlsWAQc0tsbx-5NK1rg

@jwt_user = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTgyMTEyMzd9.0_ACeZNVT3LxSuiEGdsbP_6G4yhbvPhlG6QqPOHwSKo

### Movie Index
GET http http://localhost:3000/movies.json

### Movie Show
GET http://localhost:3000/movies/3.json

### Movie Create
POST http://localhost:3000/movies.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "title": "Reign Over Me",
  "year": 2007,
  "plot": "Charlie Fineman (Adam Sandler), who lost his family in the terrorist attacks of Sept. 11, still grieves over their deaths. He runs into his former college roommate, Alan Johnson (Don Cheadle), and the two rekindle their friendship. Alan himself is feeling the strain of family and professional responsibilities, and his renewed bond with Charlie gives both men the strength to carry on during a turning point in their lives."
}

### Movie Update
PATCH http://localhost:3000/movies/8.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "director": "Rob Reiner"
}

### Movie Destroy
DELETE http://localhost:3000/movies/3.json
Authorization: Bearer {{jwt_admin}}

###

### Actor Index
GET http://localhost:3000/actors.json

### Actor Show
GET http://localhost:3000/actors/2.json

### Actor Create
POST http://localhost:3000/actors.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "first_name": "Larry",
  "last_name": "David",
  "known_for": "Curb Your Enthusiasm"
}

### Actor Update
PATCH http://localhost:3000/actors/5.json
Content-Type: application/json
Authorization: Bearer {{jwt_admin}}

{
  "known_for": "Seinfeld"
}

### Actor Destroy
DELETE http://localhost:3000/actors/18.json
Authorization: Bearer {{jwt_admin}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Noodle Test",
  "email": "Noodle@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Noodle@test.com",
  "password": "password"
}